version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install yarn@~1.7.0 -g
  pre_build:
    commands:
      - echo "pre build phase"
      - node --version
      - npm --version
      - yarn --version
  build:
    commands:
      - cd onboardor
      - echo "build phase"
      - yarn install
      - yarn run build
artifacts:
  files:
    - 'wwwroot/build/*'
