version: 0.1

phases:
  install:
    commands:
      - cd onboardor
      - curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
      - yum -y install nodejs
      - npm install yarn
      - yarn
  pre_build:
    commands:
      - echo "pre build phase"
      - node --version
      - npm --version
      - yarn --version
  build:
    commands:
      - echo "build phase"
      - yarn run build
artifacts:
  files:
    - 'wwwroot/build/*'
