version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install -y nodejs
      - npm install yarn@~1.7.0 -g
  pre_build:
    commands:
      - echo "pre build phase"
      - node --version
      - npm --version
      - yarn --version
  build:
    commands:
      - echo "build phase"
      - yarn --cwd "onboardor" install
      - yarn --cwd "onboardor" build
artifacts:
  base-directory: 'onboardor/site'
  files:
    - '**/*'